chore(migrationreact): migration react version 0.12.2 to 18.2.0
kumojin/extreme-carpaccio pull request #45
Opened 2023-01-23 14:00 UTC by DanneelsSophie

2023-01-23 14:00 UTC, DanneelsSophie commented on server/apps/backend/src/app.ts
> +  //app.use(express.static(path.join(__dirname, '../public')));
delete

2023-01-23 16:15 UTC, xballoy reviewed
J'ai juste relu le code, je n'ai pas testé manuellement pour l'instant. Je ferais des tests manuels quand tu auras fait les corrections.

2023-01-23 16:15 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerFrom.hook.ts
> +    if (!name || !url) {
C'est un bug existant, le front autorise un mot de passe vide mais pas le backend.

```suggestion
    if (!name || !url || !password) {
```

2023-01-23 16:15 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerFrom.hook.ts
> +        //TODO to fix the any type
Fix todo

2023-01-23 16:15 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerFrom.hook.ts
> +            console.error('/seller', response.statusText);
Ajouter une issue pour afficher une erreur dans le UI plutôt que dans la console.

2023-01-23 16:15 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerView/SellerView.hook.ts
> +  if (salesHistory !== undefined && sellers !== undefined) {
```suggestion
  if (salesHistory && sellers) {
```

2023-01-23 16:15 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerView/SellerView.hook.ts
> +      labels.push(i + '');
```suggestion
      labels.push(`${i}`);
```

2023-01-23 16:15 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerView/SellerView.tsx
> +      </svg>
Sortir le SVG dans un composant

2023-01-23 16:15 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerView/SellerView.tsx
> +    const eu = new Intl.NumberFormat('fr-FR', {
```suggestion
    const cash = new Intl.NumberFormat('fr-FR', {
```

2023-01-23 16:15 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerView/SellerView.tsx
> +export class SellerView extends React.Component<SellerViewProps> {
Utiliser un functionnal component

2023-01-23 16:15 UTC, xballoy commented on server/apps/frontend/package.json
> +    "start": "react-scripts start",
Est-ce que tu peux ajouter les tasks:

- `format:check`: fait un prettier check
- `format:fix`: fait un prettier fix
- `lint:check`: fait un check eslint
- `lint:fix`: fait un eslint fix

Et valider que les commandes sont bien exécutées par turbo via le package root.

2023-01-23 16:15 UTC, xballoy commented on server/apps/frontend/package.json
> +    "start": "react-scripts start",
Est-ce que cela fonctionne si on fait un start? Car le backend et le frontend ne seront pas sur le même port donc les appels ne vont pas fonctionner je pense.

2023-01-23 16:15 UTC, xballoy commented on server/apps/frontend/package.json
> +    "build": "react-scripts build",
Il faudrait aligner les commandes avec `backend/package.json` pour avoir le même comportement (sinon turbo ne va pas bien fonctionner).

2023-01-23 16:38 UTC, xballoy commented
Tu peux aussi supprimer les références à bower car on ne va plus builder le UI avec ca.

2023-01-23 19:54 UTC, DanneelsSophie commented on server/apps/frontend/src/App.test.js
> +import { render, screen } from '@testing-library/react';
Je vais même le supprimer pour l'instant :)

2023-01-23 20:10 UTC, DanneelsSophie commented on server/apps/frontend/src/Seller/SellerView/SellerView.hook.ts
> +      labels.push(i + '');
oupssss

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/.eslintrc.json
> +  "extends": [
Can you use the same plugins and rules than in eslint backend settings? It will be easier to extract the settings in a dedicated package.
For example there's already some sorting rules for the imports.

Of course you can add specific plugins/rules for React but that should be all.

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/.prettierrc.json
> +  "singleQuote": true
I don't think you need this file as there's already a .prettierrc.json in the root folder.

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/index.html
> +</html>
You still use the template from Create React App. The one from Vite is enough and simpler.

```suggestion
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Extreme carpaccio</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand mb-1 h6" href="#">Extreme carpaccio</a>
        </div>
      </div>
    </nav>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
```

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/jest.config.js
> +module.exports = {
Remove, we'll add one if we add jest tests.

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/package.json
> +  },
You don't need this because you added an .eslintrc.json file.

```suggestion

```

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/package.json
> +    "eslint-plugin-simple-import-sort": "~9.0.0",
Cf my comment on the eslintrc file. Use the same plugin / setup for eslint than the backend.

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/package.json
> +    "prettier": "~2.8.3",
You don't need it, it's already included in the server/package.json file.

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/package.json
> +    "@types/jest": "~27.5.2",
We don't need those (no tests)

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/package.json
> +    "prop-types": "~15.8.1",
We dont need this one, as we migrated everything to TypeScript

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/package.json
> +    "lodash": "~4.17.21",
Do we really need lodash? We can probably replace it with vanilla JS.

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/package.json
> +    "webpack-cli": "~5.0.1",
Do you really need to import webpack dependencies explicitly?

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/package.json
> +    "@types/react-dom": "~18.0.9",
Those should go to dependencies (`@types` should be in the same object that the lib as they are not included in the build anyway).

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/src/App.tsx
> +
Same comment for everywhere: don't add an empty line between every import group.

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/src/App.tsx
> +function App(): JSX.Element {
Use arrow functions everywhere + you shouldn't need to add JSX.Element on compoment

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/src/Seller/Seller.hook.ts
> +// eslint-disable-next-line  @typescript-eslint/consistent-type-definitions
We should remove this exception once the eslint are aligned with the backend. 

But if you really wanted to use a type it would be better to override the rule in the eslintrc file than adding an exception everywhere.

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/src/Seller/Seller.hook.ts
> +  addSeller: (s: Seller) => void;
```suggestion
  addSeller: (seller: Seller) => void;
```

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerForm.container.tsx
> +interface SellerFormContainerProps {
Use type instead of interface.

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerForm.tsx
> +        Warning: There is an error.
Could we add a more detailed error? That message doesn't really help.

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerFrom.hook.ts
> +  const [isError, setIsError] = React.useState<boolean>(false);
It's not clear with the name what's in error. 

```suggestion
  const [hasError, setHasError] = React.useState<boolean>(false);
```

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerView/SellerView.hook.ts
> +  if (salesHistory?.history != null) {
```suggestion
  if (salesHistory?.history) {
```

2023-01-27 23:25 UTC, xballoy commented on server/apps/frontend/src/setupTests.js
> +import '@testing-library/jest-dom';
Remove, there's no tests

2023-01-27 23:28 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerForm.tsx
> +            <input
Add `required` on the fields so we have a basic validation thanks to HTML5

2023-02-01 22:52 UTC, xballoy reviewed
A few remaining comments and I think it will be good 👍

2023-02-01 22:52 UTC, xballoy commented on clients/javascript/express/server.js
> +var http = require("http");
Do not change `clients/*` files

2023-02-01 22:52 UTC, xballoy commented on server/apps/frontend/.eslintrc.json
> +    "airbnb-base",
You should use `airbnb` instead of `airbnb-base` here as it will contains rules specific to React we don't need in the backend.

2023-02-01 22:52 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerFrom.hook.ts
> +    }
Could you add 3 ifs to says which field is missing?

2023-02-01 22:52 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerForm.tsx
> +        the facilitator/read the README for help
```suggestion
        {errorForm.message}
```

2023-02-01 22:52 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerFrom.hook.ts
> +              message: `The is a warning : ${response.statusText}`,
```suggestion
              message: 'An error occurred during registration',
```

2023-02-01 22:52 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerFrom.hook.ts
> +            message: `The is a an error : ${err}`,
```suggestion
            message: `An error occured during registration: ${err}`,
```

2023-02-01 22:52 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerView/SellerView.hook.ts
> +export interface GetDataHistoryReturned {
Use type instead of interface everywhere please.

2023-02-01 22:52 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerView/SellerView.tsx
> +const getArraySeller = ({ sellers }: SellerContentProps): JSX.Element[] =>
Remove `: JSX.Element` in this file

2023-02-02 13:21 UTC, xballoy reviewed
I'll do some manual testing later today but it looks (almost) good.

2023-02-02 13:21 UTC, xballoy commented on clients/javascript/express/server.js
> +  server.start = server.listen.bind(server, process.env.PORT || 4000);
Do not change clients please!

2023-02-02 13:21 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerFrom.hook.ts
> +        message: 'password is required',
```suggestion
        message: 'url is required',
```

2023-02-06 21:38 UTC, xballoy requested changes
Can you fix this comments and update your branch with main? Otherwise it's good to merge.

2023-02-06 21:38 UTC, xballoy commented on server/apps/frontend/src/Seller/Seller.hook.ts
> +    setSellers((sellersParam: Seller[]) => [...sellersParam, seller].sort());
You sort an array of `Seller`, not sure what it does but probably not what you expect.

2023-02-06 21:38 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerFrom.hook.ts
> +            console.error('/seller', response.statusText);
You can remove this console.error now we show a message in the UI.

2023-02-06 21:38 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerFrom.hook.ts
> +          console.error('/seller', err);
You can remove this console.error now we show a message in the UI.

2023-02-06 21:38 UTC, xballoy commented on server/apps/frontend/package.json
> +  "name": "extreme-carpaccio-server-front",
So we have a `backend` and a `frontend`

```suggestion
  "name": "frontend",
```

2023-02-06 21:38 UTC, xballoy commented on server/apps/backend/package-lock.json
> +{
You don't need this file if you run `npm install` from `server/`

2023-02-06 21:38 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerForm.tsx
> +interface SellerFormProps {
As already suggested on several other comments, prefer `type`

2023-02-06 21:38 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerForm/SellerForm.container.tsx
> +interface SellerFormContainerProps {
As already suggested on several other comments, prefer `type`

2023-02-06 21:38 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerView/SellerView.container.tsx
> +interface SellerViewContainerProps {
As already suggested on several other comments, prefer `type`

2023-02-06 21:38 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerView/SellerView.tsx
> +interface SellerViewProps {
As already suggested on several other comments, prefer `type`

2023-02-06 21:38 UTC, xballoy commented on server/apps/frontend/src/Seller/SellerView/SellerView.tsx
> +import { getDataHistory, options, stringToColor } from './SellerView.hook';
A good rule of thumb is to have you `import 'xxx'` either first or last, not mixed in between imports.

```suggestion
import { SalesHistory, Seller } from '../Seller.hook';
import { getDataHistory, options, stringToColor } from './SellerView.hook';
import '@formatjs/intl-numberformat/polyfill';
import '@formatjs/intl-numberformat/locale-data/fr';
```

2023-02-06 21:38 UTC, xballoy commented on server/apps/frontend/src/Seller/Seller.hook.ts
> +    if (dataSellers != null) {
Always use `===` and `!==`

```suggestion
    if (!dataSellers) {
```

2023-02-06 21:38 UTC, xballoy commented on server/apps/frontend/package.json
> +    "eslint-config-airbnb": "19.0.4",
You're missing some plugins: `eslint-plugin-react-hooks` and `eslint-plugin-jsx-a11y`

> Our default export contains most of our ESLint rules, including ECMAScript 6+ and React. It requires eslint, eslint-plugin-import, eslint-plugin-react, eslint-plugin-react-hooks, and eslint-plugin-jsx-a11y. Note that it does not enable our React Hooks rules. To enable those, see the [eslint-config-airbnb/hooks section](https://www.npmjs.com/package/eslint-config-airbnb#eslint-config-airbnbhooks).

https://www.npmjs.com/package/eslint-config-airbnb

2023-02-06 21:38 UTC, xballoy commented on server/apps/frontend/.eslintrc.json
> +    "@typescript-eslint/consistent-type-definitions":  "off",
```suggestion
    "@typescript-eslint/consistent-type-definitions": ["error", "type"],
```

2023-02-06 21:38 UTC, xballoy commented on server/apps/frontend/.eslintrc.json
> +    "@typescript-eslint/require-array-sort-compare": "warn",
```suggestion

```

2023-02-07 17:53 UTC, xballoy commented on server/apps/frontend/.eslintrc.json
> +    "@typescript-eslint/require-array-sort-compare": "warn",
Can you please remove this override.

2023-02-07 20:55 UTC, xballoy approved these changes

2023-02-07 21:05 UTC, merged